### ISSUE TITLE
stratum

### ISSUE THREAD

**Issue by lejeczek** [sammy007/homebrew-monero#1]
hi sammy007, any chance you could create "issues" for your stratum?
I'd like to ask you something, I have a problem with stratum.
many thanks, L.

**Comment by sammy007** [comment]
Nope.

**Comment by lejeczek** [comment]
Gee, really? How then we can ask and/or seek any technical help from you on monero-stratum?

**Comment by lejeczek** [comment]
I'm thinking ... just in case you misunderstood me - I mean "issues" tab in github so we users could report problems and ask questions, no?

**Comment by sammy007** [comment]
There is no technical help, especially for people who are blatant enough to spam in other projects. This project does not make any sense because you must own million worth of hardware to solo mine it. Period. I am tired of ignorants spamming me with help requests. It's a bug tracker, not a fucking help desk. use reddit/Monero or other shit if you need assistance.
